default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['pg_username'] %>
  password: <%= ENV['pg_password'] %>
  port: 5433

development:
  <<: *default
  database: <%= ENV['development_database'] %>

test:
  <<: *default
  database: <%= ENV['test_database'] %>